### ISSUE TITLE
minimum size set error

### ISSUE THREAD

**Issue by sprinoniong** [d4rken-org/sdmaid-se#1813]
no value can entered

**Describe the bug**

**To Reproduce**
1. just language set korean(system default)

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**
/[ if change language english there no error

![Image](https://github.com/user-attachments/assets/aa33591a-f600-40c5-8e71-c4865684148d)

](url)

**Comment by sprinoniong** [comment]
1.4.10-re0  i download it at play store

**Comment by d4rken** [comment]
Should be fixed in v1.4.11, please try and report back.

**Comment by sprinoniong** [comment]
> Should be fixed in v1.4.11, please try and report back. (Re [#1760](https://github.com/d4rken-org/sdmaid-se/pull/1760))

The situation is still the same. If I change it to English, it works, but when I set the system language to Korean, it gives me an error.


![Image](https://github.com/user-attachments/assets/5afa6dac-47c4-403a-9618-fc8f6169f781)
![Image](https://github.com/user-attachments/assets/a862c20b-290d-4819-bd67-e289fd2f93ba)
![Image](https://github.com/user-attachments/assets/49d527ea-eeb4-45ff-b8e2-7a55803688e1)

**Comment by sprinoniong** [comment]
It happens in both cases. It happens when the default language of the phone is Korean, and if you change it to English in the app settings, it works fine. It's the same when you use the English keyboard.
