### ISSUE TITLE
root and accessibility 

### ISSUE THREAD

**Issue by JesseRacine** [d4rken-org/sdmaid-se#23]
I've given the app root access but it can't access as many file system locations as the original SD Maid can. I get filesystem errors when trying to clear files even though it has root.

Also, right now it doesn't appear to be able to leave the accessibility permissions turned off but still clear caches with root enabled. I'd prefer to leave accessibility turned off and just allow root permissions to access the data.

I'm able to do this with the original SD Maid.

**Comment by d4rken** [comment]
Fully agree. I thought this would already work, will look into it.

**Comment by Rokcy98** [comment]
The problem doesn't seem to be solved: rooted here, when trying to clean apps it tells me accessibility service is no more enabled, and it can't clean

**Comment by d4rken** [comment]
Can you get me a debug log of this?

**Comment by d4rken** [comment]
Are you sure you are on the latest build?
Should be fixed as of 0.6.5-beta0.
Couldn't reproduce on a Pixel 3A :slightly_frowning_face:

**Comment by Rokcy98** [comment]
![Screenshot_20230326-183808](https://user-images.githubusercontent.com/62332789/227790540-59a1dea8-2672-452a-8464-ec6323684792.jpg)
This one is with "include inaccessible data" enabled, root and no accessibility

![Screenshot_20230326-183823](https://user-images.githubusercontent.com/62332789/227790538-39ebea5d-c223-496f-bae9-840c0b058911.jpg)
This one with "include inaccessible data" disabled, root and no accessibility

**Comment by JesseRacine** [comment]
Here is a log file from me with the latest version. This is where I try to delete app files and the app complains about accessibility not being enabled, even though it has root.
[eu.darken.sdmse_logfile_1679747982086.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11072323/eu.darken.sdmse_logfile_1679747982086.log.zip)

**Comment by d4rken** [comment]
If you go into settings and setup, can you show me the accessibility setup card?

**Comment by Rokcy98** [comment]
![Screenshot_20230326-190523](https://user-images.githubusercontent.com/62332789/227792078-90a57e5a-b939-4a1d-82cf-da19b06ebf84.jpg)

**Comment by Rokcy98** [comment]
It seems like that @JesseRacine and I are talking about the same exact problem btw, we should have the ability to bypass accessibility permission with root, like on sd maid

**Comment by d4rken** [comment]
@Rokcy98  SD Maid has no root in your first or second log.
Check Magisk and make sure SD Maid actually has root access.

@JesseRacine I don't think your log is from 0.6.5-beta0, please update and try again. The log seems to be from 0.6.4 or earlier and only contains a bit of the accessibility service and lots of SystemCleaner entries. Make sure you start the log before the error occurs.

**Comment by JesseRacine** [comment]
> @JesseRacine I don't think your log is from 0.6.5-beta0, please update and try again. The log seems to be from 0.6.4 or earlier and only contains a bit of the accessibility service and lots of SystemCleaner entries. Make sure you start the log before the error occurs.

@d4rken  I'm sorry about that, I had uploaded the wrong log and I wasn't even on the proper beta. I've switched to the correct beta and recorded a log for you. Please see here.
[eu.darken.sdmse_logfile_1679861946459.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11072982/eu.darken.sdmse_logfile_1679861946459.log.zip)

**Comment by d4rken** [comment]
> @d4rken I'm sorry about that, I had uploaded the wrong log and I wasn't even on the proper beta. I've switched to the correct beta and recorded a log for you. Please see here. [eu.darken.sdmse_logfile_1679861946459.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11072982/eu.darken.sdmse_logfile_1679861946459.log.zip)

Also looks like no root. While the log doesn't contain the AppCleaner search, the init info only shows public storage, if SD Maid loaded with root, it should also display private data areas.

What does Magisk show for SD Maid SE?

```
023-03-26T20:19:06.463Z  I/SDMSE:Debug:Log:Recorder:Module: Data areas: (4)
2023-03-26T20:19:06.463Z  I/SDMSE:Debug:Log:Recorder:Module: #0 DataArea(path=LocalPath(/storage/emulated/0), type=SDCARD, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@2e490c1, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
2023-03-26T20:19:06.463Z  I/SDMSE:Debug:Log:Recorder:Module: #1 DataArea(path=LocalPath(/storage/emulated/0/Android/media), type=PUBLIC_MEDIA, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@5c2b7af, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
2023-03-26T20:19:06.463Z  I/SDMSE:Debug:Log:Recorder:Module: #2 DataArea(path=SAFFile(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, obb]), type=PUBLIC_OBB, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@839b7bc, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
2023-03-26T20:19:06.463Z  I/SDMSE:Debug:Log:Recorder:Module: #3 DataArea(path=SAFFile(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, data]), type=PUBLIC_DATA, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@df6b345, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
```

**Comment by JesseRacine** [comment]
Hmmm, I'm not sure how to get it working with root then. SD Maid will request access for root and I grant it, and the root access shows up in Magisk. Here's a screenshot.
![photo_2023-03-26_16-40-24](https://user-images.githubusercontent.com/9375408/227803411-bba248c0-2992-424c-864a-619f683352a2.jpg)

**Comment by d4rken** [comment]
Can you do this:

* Start debug log
* Force stop SD Maid
* Open SD Maid
* Go to Settings > Setup  (just open the screen)
* Then return to the dashboard again and scan + delete AppCleaner
* Stop and share the debug log with me.

Something with how SD Maid uses root seems to be broken?

**Comment by JesseRacine** [comment]
Ok, please see here.

[eu.darken.sdmse_logfile_1679866180526.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11073134/eu.darken.sdmse_logfile_1679866180526.log.zip)

**Comment by jont4** [comment]
same problem here.
Using latest version, root it's OK, but complains about accessibility

**Comment by d4rken** [comment]
Seems this is not related to accessibility at all so far.
Root just isn't working :frowning: 
Not yet sure why.

```
2023-03-26T21:30:15.451Z  D/SDMSE:Root:Java:Client: Instantiating RootHost launcher...
2023-03-26T21:30:15.451Z  D/SDMSE:Root:Java:Host:Launcher: Initiating connection to host.
2023-03-26T21:30:15.451Z  D/SDMSE:Root:Host:Launcher: createConnection(class eu.darken.sdmse.common.root.javaroot.JavaRootConnection,class eu.darken.sdmse.common.root.javaroot.JavaRootHost,true,false)
2023-03-26T21:30:15.452Z  I/SDMSE:Root:Host:Launcher: Initiating connection to host(class eu.darken.sdmse.common.root.javaroot.JavaRootHost) via binder(class eu.darken.sdmse.common.root.javaroot.JavaRootConnection)
2023-03-26T21:30:15.458Z  D/SDMSE:RootHostCmdBuilder: build(relocate=false, RootHostOptions(packageName=eu.darken.sdmse, pairingCode=548535a6-87e2-4fbc-8f25-dde0c977e3f0, isDebug=true, isTrace=true, waitForDebugger=false))
2023-03-26T21:30:15.458Z  D/SDMSE:Root:Java:Host:CmdBuilder: Launch command: CLASSPATH=/data/app/~~2aVVmN_YhxlSkdW32iPOsA==/eu.darken.sdmse-U_zMY__op8gPKxFjzkReeg==/base.apk exec /proc/14587/exe -XjdwpProvider:adbconnection -XjdwpOptions:suspend=n,server=y /system/bin --nice-name=eu.darken.sdmse:root:eu.darken.sdmse.common.root.javaroot.JavaRootHost eu.darken.sdmse.common.root.javaroot.JavaRootHost
2023-03-26T21:30:15.458Z  D/SDMSE:Root:Java:Host:CmdBuilder: Launch command with options: CLASSPATH=/data/app/~~2aVVmN_YhxlSkdW32iPOsA==/eu.darken.sdmse-U_zMY__op8gPKxFjzkReeg==/base.apk exec /proc/14587/exe -XjdwpProvider:adbconnection -XjdwpOptions:suspend=n,server=y /system/bin --nice-name=eu.darken.sdmse:root:eu.darken.sdmse.common.root.javaroot.JavaRootHost eu.darken.sdmse.common.root.javaroot.JavaRootHost ROOT_HOST_OPTIONS=PQAAAGUAdQAuAGQAYQByAGsAZQBuAC4AcwBkAG0AcwBlAC4AYwBvAG0AbQBvAG4ALgByAG8AbwB0AC4AagBhAHYAYQByAG8AbwB0AC4AaQBuAHQAZQByAG4AYQBsAC4AUgBvAG8AdABIAG8AcwB0AE8AcAB0AGkAbwBuAHMAAAAPAAAAZQB1AC4AZABhAHIAawBlAG4ALgBzAGQAbQBzAGUAAAAkAAAANQA0ADgANQAzADUAYQA2AC0AOAA3AGUAMgAtADQAZgBiAGMALQA4AGYAMgA1AC0AZABkAGUAMABjADkANwA3AGUAMwBmADAAAAAAAAEAAAABAAAAAAAAAA==
2023-03-26T21:30:15.458Z  D/SDMSE:ProducerCoroutine: RootHost launch command is eu.darken.rxshell.cmd.Cmd$Builder@bdca6dc
2023-03-26T21:30:15.850Z  D/SDMSE:Root:Host:Launcher: Root host launch result was: Cmd.Result(cmd=Cmd(timeout=0, commands=[CLASSPATH=/data/app/~~2aVVmN_YhxlSkdW32iPOsA==/eu.darken.sdmse-U_zMY__op8gPKxFjzkReeg==/base.apk exec /proc/14587/exe -XjdwpProvider:adbconnection -XjdwpOptions:suspend=n,server=y /system/bin --nice-name=eu.darken.sdmse:root:eu.darken.sdmse.common.root.javaroot.JavaRootHost eu.darken.sdmse.common.root.javaroot.JavaRootHost ROOT_HOST_OPTIONS=PQAAAGUAdQAuAGQAYQByAGsAZQBuAC4AcwBkAG0AcwBlAC4AYwBvAG0AbQBvAG4ALgByAG8AbwB0AC4AagBhAHYAYQByAG8AbwB0AC4AaQBuAHQAZQByAG4AYQBsAC4AUgBvAG8AdABIAG8AcwB0AE8AcAB0AGkAbwBuAHMAAAAPAAAAZQB1AC4AZABhAHIAawBlAG4ALgBzAGQAbQBzAGUAAAAkAAAANQA0ADgANQAzADUAYQA2AC0AOAA3AGUAMgAtADQAZgBiAGMALQA4AGYAMgA1AC0AZABkAGUAMABjADkANwA3AGUAMwBmADAAAAAAAAEAAAABAAAAAAAAAA==]), exitcode=-3, output.size()=0, errors.size()=0)
2023-03-26T21:30:15.851Z  D/SDMSE:Root:Host:Launcher: Canceling!
2023-03-26T21:30:15.852Z  E/SDMSE:Root:Java:Host:Launcher: Failed to establish connection: eu.darken.sdmse.common.root.javaroot.internal.RootException: Shell died launching the java root host.
```

**Comment by d4rken** [comment]
Found the issue. Proguard/R8 was removing important code related to root operations in release mode.

Should be fixed in the next release. Thanks for detailed logs!

Double bug this one, nice catch :smile:.

**Comment by JesseRacine** [comment]
Ok I'll be able to test it out later today.

I have another possible root issue where system files can't be accessed with root. I can test that out again too. If I still have problems with the system files I'm going to compare the behavior with the original SD Maid first before giving any more details.

**Comment by jont4** [comment]
here it's OK now.
Root working as expected
