### ISSUE TITLE
Planned app cleaner restarts on Android 14 again and again

### ISSUE THREAD

**Issue by MartinL0815** [d4rken-org/sdmaid-se#716]
**Describe the bug**
After updating to Android 14 on my Google Pixel 5 the app cleaner starts again and again.

**To Reproduce**
1. Activated a time plan in the planner with activated app cleaner

**Expected behavior**
Like with Android 13 I expect the planned app cleaner to not come up again after finishing.

**Smartphone (please complete the following information):**
 - Pixel 5
 - OS: Android 14
 - Root status: not rooted
 - SD Maid 2/SE version: V0.14.0-beta0 (1400000) ~ 42d46889/ GPLAY/BETA

**Comment by MarkyMarkDE** [comment]
See #692 and #693
this here is a duplicate of the previous named tickets

**Comment by MartinL0815** [comment]
The only special is, that it worked with Android 13.
The only issue was to start the cleaning and wait for unlocking the phone to really start cleaning and to succeed.
Something I didn't report.

**Comment by Koraikoaw** [comment]
I am also having this bug in Android 13 on a Samsung Galaxy S21. I triggered it manually, and app cleaner never completes, it just loops back to the start, with the accessibility service of the app basically taking over my phone. Ended up having to restart in order to stop the cycle.

**Comment by d4rken** [comment]
@Koraikoaw are you on the latest version? This should be fixed in 0.15.2. In that version you should be able to cancel any accessibility action by turning off your screen and/or enabling the lockscreen.

**Comment by MarkyMarkDE** [comment]
Yes, the bug still exists in 0.15.2-beta0-foss.
Also the app does not recognize that the scheduled run today has done.

![Screenshot_20231017-205614](https://github.com/d4rken-org/sdmaid-se/assets/12845477/21054ed3-4bbc-4772-b0da-7ca4b47cfa46)

**Comment by d4rken** [comment]
> Yes, the bug still exists in 0.15.2-beta0-foss.

So the scheduler still restarts multiple times within minutes? :frowning:

Can anyone provide me with a debug log of this behavior?
 

> Also the app does not recognize that the scheduled run today has already done.

I think an error was thrown during the process. If an error occurs it will skip the remaining code, which includes updating the last execution timestamp.

**Comment by MarkyMarkDE** [comment]
> > Yes, the bug still exists in 0.15.2-beta0-foss.
> 
> So the scheduler still restarts multiple times within minutes? 😦
> 
> Can anyone provide me with a debug log of this behavior?
> 
> > Also the app does not recognize that the scheduled run today has already done.
> 
> I think an error was thrown during the process. If an error occurs it will skip the remaining code, which includes updating the last execution timestamp.

Yes, the schedule starts and starts again, in which repeating time don't know, have unfortunately not looked at the watch.
Today I need to kill the app and tomorrow I will guess, all is fine but at the follow day, the bug is again.
Hope I can provide a log in few days.

**Comment by MarkyMarkDE** [comment]
> > Yes, the bug still exists in 0.15.2-beta0-foss.
> 
> So the scheduler still restarts multiple times within minutes? 😦
> 
> Can anyone provide me with a debug log of this behavior?
> 
> > Also the app does not recognize that the scheduled run today has already done.
> 
> I think an error was thrown during the process. If an error occurs it will skip the remaining code, which includes updating the last execution timestamp.

on AndroidTV is the same Bug in the current beta

**Comment by MarkyMarkDE** [comment]
> > Yes, the bug still exists in 0.15.2-beta0-foss.
> 
> So the scheduler still restarts multiple times within minutes? 😦
> 
> Can anyone provide me with a debug log of this behavior?
> 
> > Also the app does not recognize that the scheduled run today has already done.
> 
> I think an error was thrown during the process. If an error occurs it will skip the remaining code, which includes updating the last execution timestamp.

the scheduler runs exactly every 10 minutes

**Comment by MarkyMarkDE** [comment]
@d4rken Also, am Tag wo ich SDMaid neu starten muss oder die App aktualisiere ist der zeitgesteuerte Prozess ohne Probleme und startet nicht alle 10 Minuten neu.
Am Folgetag funktioniert es nicht mehr, auf AndroidTV und Android 14 da selbe.
Habe mal vom Android 14 einen log beigefügt, hoffe, er hilft dir das Problem zu finden und zu beheben.

[eu.darken.sdmse_logfile_1697997975490.log.zip](https://github.com/d4rken-org/sdmaid-se/files/13064216/eu.darken.sdmse_logfile_1697997975490.log.zip)

**Comment by d4rken** [comment]
#752 might fix this.

Closing this issue in favor of #692 though as I think it's the same issue. Please continue reports there.

@Koraikoaw Canceling the accessibility should be as easy as turning off the screen now. You should NOT have to reboot, if this is still an issue, please open a new ticket.

> Das witzige ist, wenn ich jetzt nach dem zwangsbeenden der App und neustarten schaue, wird mir tatsächlich die korrekte Zeit der letzten Ausführung gezeigt. Ohne zwangsbeenden und neustarten bleibt es bei letzter Ausführung Gestern.

Don't know why this would happen :thinking: 

> Dafür gibt es auf AndroidTV den Bug dass ich nach dem zwangsbeenden und neustarten, mehrfach die Bedienungshilfen für SDMaid ein und aus schalten muß, bis dieser korrekt eingeschaltet wird.

Force stopping an app will also kill the accessibility service. If an accessibility service is crashing or being killed too often, Android may block it until reboot.

Turning it on once should be enough, but there may be some special behavior on Android TV. Note that it may take a few seconds until it starts.

If possible you can grant SD Maid the ability to turn the service on/off automatically:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-automatic-service-restart

**Comment by MarkyMarkDE** [comment]
> #752 might fix this.
> 
> Closing this issue in favor of #692 though as I think it's the same issue. Please continue reports there.
> 
> @Koraikoaw Canceling the accessibility should be as easy as turning off the screen now. You should NOT have to reboot, if this is still an issue, please open a new ticket.
> 
> > Das witzige ist, wenn ich jetzt nach dem zwangsbeenden der App und neustarten schaue, wird mir tatsächlich die korrekte Zeit der letzten Ausführung gezeigt. Ohne zwangsbeenden und neustarten bleibt es bei letzter Ausführung Gestern.
> 
> Don't know why this would happen 🤔
> 
> > Dafür gibt es auf AndroidTV den Bug dass ich nach dem zwangsbeenden und neustarten, mehrfach die Bedienungshilfen für SDMaid ein und aus schalten muß, bis dieser korrekt eingeschaltet wird.
> 
> Force stopping an app will also kill the accessibility service. If an accessibility service is crashing or being killed too often, Android may block it until reboot.
> 
> Turning it on once should be enough, but there may be some special behavior on Android TV. Note that it may take a few seconds until it starts.
> 
> If possible you can grant SD Maid the ability to turn the service on/off automatically: https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-automatic-service-restart

Yes, this behavior is really funny.
Hope you see in my last attached log what's going on here.

Not possible to grant the permissions.

Aaahh, the accessibility mode will be killed too, this I didn't know before.
Sure then it need some seconds before it starts again.
